server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Hari@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    datasource-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

#configuration for eureka client
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#  service-url:
#    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
    tracing:
      sampling:
        probability: 1.0