server:
  port: 9296

Spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sarkiharish/spring-app-config.git
          clone-on-start: true

#configuration for eureka client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
  service-url:
    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}