server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
    password: Hari@123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    datasource-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-57985744.okta.com/oauth2/default
        client:
          registration:
            internal-client:
              provider: okta
              authorization-grant-type: client_credentials
              scope: internal
              client-id: 0oabjl3m6iHlPrdct5d7
              client-secret: 2ZtrXU7BN_OF9hC9ZoCv56nUdV50GquW7uG44gzCnIhHuWbqwW3EXICuga194qph
          provider:
            okta:
              issuer-uri: https://dev-57985744.okta.com/oauth2/default

#configuration for eureka client
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true
#  service-url:
#    defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0


resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

